spring:
  application:
    name: securityDemo
  security:
    user:
      name: admin
      password: chirayu
  datasource:
    url: jdbc:postgresql://localhost:5432/securityddemo
    username: postgres
    password: Chirayu@1911
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
app:
  jwtSecret: hYGfufhViLAeahV3RUlgiNY2SuwJjY2wVtB5L/QajzQ=
  jwtExpirationMs: 360000

logging:
  level:
    org:
      springframework: debug
      security: debug
      securityDemo: debug

